// Error: continue outside of a loop
package main

func main () {
	continue
}